module.exports = {
  4000: "Southern Region Office : Southern Regional Office : IS STORE",
  4001: "Tamil Nadu State Office : Arakonam AFS : IS STORE",
  4002: "Tamil Nadu State Office : Coimbatore AFS : IS STORE",
  4003: "Tamil Nadu State Office : Meenambakkam AFS : IS STORE",
  4004: "Tamil Nadu State Office : Trichy AFS : IS STORE",
  4005: "Tamil Nadu State Office : Sulur AFS : IS STORE",
  4006: "Tamil Nadu State Office : Madurai AFS : IS STORE",
  4007: "Tamil Nadu State Office : Tambaram AFS : IS STORE",
  4028: "Tamil Nadu State Office : Tuticorin AFS : IS STORE",
  4038: "Tamil Nadu State Office : Ramnad AFS : IS STORE",
  4076: "Tamil Nadu State Office : Tondiarpet Drum Plant : IS STORE",
  4100: "Tamil Nadu State Office : Tamil Nadu State Office : IS STORE",
  4101: "Tamil Nadu State Office : Coimbatore DO : IS STORE",
  4102: "Tamil Nadu State Office : Chennai DO : IS STORE",
  4103: "Tamil Nadu State Office : Madurai DO : IS STORE",
  4104: "Tamil Nadu State Office : Salem DO : IS STORE",
  4105: "Tamil Nadu State Office : Trichy DO : IS STORE",
  4111: "Tamil Nadu State Office : Coimbatore AO : IS STORE",
  4112: "Tamil Nadu State Office : Chennai AO : IS STORE",
  4113: "Tamil Nadu State Office : Madurai AO : IS STORE",
  4114: "Tamil Nadu State Office : Trichy AO : IS STORE",
  4121: "Tamil Nadu State Office : RCO/CPCL Manali : IS STORE",
  4125: "Tamil Nadu State Office : Madurai TOP : IS STORE",
  4126: "Tamil Nadu State Office : Madurai Terminal : IS STORE",
  4127: "Tamil Nadu State Office : Korukkupet Tml : IS STORE",
  4129: "Tamil Nadu State Office : Tondiarpet Tml : IS STORE",
  4130: "Tamil Nadu State Office : Tuticorin Tml : IS STORE",
  4133: "Tamil Nadu State Office : Trichy TOP : IS STORE",
  4134: "Tamil Nadu State Office : Chennai FST : IS STORE",
  4135: "Tamil Nadu State Office : CBMT Narimanam : IS STORE",
  4136: "Tamil Nadu State Office : LBP Chennai : IS STORE",
  4141: "Tamil Nadu State Office : Asanur TOP : IS STORE",
  4149: "Tamil Nadu State Office : Coimbatore Irugur Terminal : IS STORE",
  4150: "Tamil Nadu State Office : Coimbatore Terminal : IS STORE",
  4159: "Tamil Nadu State Office : HPCL ENNORE : IS STORE",
  4167: "Tamil Nadu State Office : RIL Ennore : IS STORE",
  4170: "Tamil Nadu State Office : Chennai Jetty Project : IS STORE",
  4171: "Tamil Nadu State Office : Ennore BP : IS STORE",
  4172: "Tamil Nadu State Office : Salem BP : IS STORE",
  4174: "Tamil Nadu State Office : Pondicherry BP : IS STORE",
  4175: "Tamil Nadu State Office : Madurai BP : IS STORE",
  4176: "Tamil Nadu State Office : Mayiladuthurai BP : IS STORE",
  4177: "Tamil Nadu State Office : Erode BP : IS STORE",
  4179: "Tamil Nadu State Office : Coimbatore BP : IS STORE",
  4181: "Tamil Nadu State Office : Trichy BP : IS STORE",
  4183: "Tamil Nadu State Office : Chengelpet BP : IS STORE",
  4184: "Tamil Nadu State Office : Mannargudi BP : IS STORE",
  4185: "Tamil Nadu State Office : Coimbatore Bottling Plant : IS STORE",
  4187: "Tamil Nadu State Office : Ilayangudi BP : IS STORE",
  4188: "Tamil Nadu State Office : Tirunelveli BP : IS STORE"
};
